from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PREDICTION_SCORES_PATH = (
    ROOT / "data" / "outputs" / "dashboard" / "feature_43_mvp" / "prediction_scores.csv"
)
OUTPUT_DIR = ROOT / "data" / "outputs" / "modeling" / "feature_43_xgboost" / "diagnostics"
DEFAULT_THRESHOLD = 0.5


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export diagnostic tables and a Korean report for the 43-feature XGBoost model."
    )
    parser.add_argument(
        "--prediction-scores",
        type=Path,
        default=PREDICTION_SCORES_PATH,
        help="prediction_scores.csv generated by export_feature_43_dashboard_artifacts.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Directory where model diagnostic artifacts will be written.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help=(
            "Primary decision threshold to use for segment and error diagnostics. "
            "If omitted, the script uses prediction_scores.csv's threshold column."
        ),
    )
    parser.add_argument(
        "--top-error-cases",
        type=int,
        default=15,
        help="Number of false positive/false negative examples to keep in error_cases.csv.",
    )
    return parser.parse_args()


def _safe_float(value: object) -> float | None:
    if value is None:
        return None
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return None
    if np.isnan(numeric):
        return None
    return numeric


def _round_or_none(value: object, digits: int = 4) -> float | None:
    numeric = _safe_float(value)
    if numeric is None:
        return None
    return round(numeric, digits)


def _read_prediction_scores(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Prediction scores file not found: {path}. "
            "Run scripts/export_feature_43_dashboard_artifacts.py first."
        )
    frame = pd.read_csv(path, encoding="utf-8-sig")
    required_columns = {
        "split",
        "market",
        "stock_code",
        "corp_name",
        "fiscal_year",
        "industry_macro_category",
        "is_speculative",
        "prob_speculative",
    }
    missing_columns = sorted(required_columns - set(frame.columns))
    if missing_columns:
        raise KeyError(f"prediction_scores.csv is missing required columns: {missing_columns}")
    frame = frame.copy()
    frame["is_speculative"] = frame["is_speculative"].astype(int)
    frame["prob_speculative"] = pd.to_numeric(frame["prob_speculative"], errors="coerce")
    return frame


def _resolve_primary_threshold(scores: pd.DataFrame, override: float | None) -> float:
    if override is not None:
        return override
    threshold_column = scores.get("threshold")
    if threshold_column is None:
        return DEFAULT_THRESHOLD
    candidates = [
        numeric
        for numeric in (_safe_float(value) for value in threshold_column.dropna().unique())
        if numeric is not None
    ]
    if not candidates:
        return DEFAULT_THRESHOLD
    return float(candidates[0])


def _metrics_for_frame(frame: pd.DataFrame, threshold: float) -> dict[str, float | int | None]:
    from sklearn.metrics import (
        average_precision_score,
        log_loss,
        roc_auc_score,
    )

    y_true = frame["is_speculative"].astype(int)
    probabilities = pd.to_numeric(frame["prob_speculative"], errors="coerce")
    valid_mask = probabilities.notna()
    y_true = y_true.loc[valid_mask]
    probabilities = probabilities.loc[valid_mask]
    predictions = (probabilities >= threshold).astype(int)

    true_positive = int(((y_true == 1) & (predictions == 1)).sum())
    true_negative = int(((y_true == 0) & (predictions == 0)).sum())
    false_positive = int(((y_true == 0) & (predictions == 1)).sum())
    false_negative = int(((y_true == 1) & (predictions == 0)).sum())
    has_two_classes = y_true.nunique() == 2
    logloss_value: float | None = None
    if has_two_classes:
        clipped_probabilities = np.clip(probabilities.to_numpy(dtype=float), 1e-15, 1 - 1e-15)
        logloss_value = float(log_loss(y_true, clipped_probabilities))
    precision_denominator = true_positive + false_positive
    recall_denominator = true_positive + false_negative
    specificity_denominator = true_negative + false_positive
    precision = true_positive / precision_denominator if precision_denominator else 0.0
    recall = true_positive / recall_denominator if recall_denominator else 0.0
    specificity = true_negative / specificity_denominator if specificity_denominator else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    accuracy = (true_positive + true_negative) / len(y_true) if len(y_true) else None
    balanced_accuracy = (recall + specificity) / 2 if has_two_classes else None

    return {
        "rows": len(y_true),
        "positive_rows": int(y_true.sum()),
        "positive_rate": float(y_true.mean()) if len(y_true) else None,
        "threshold": float(threshold),
        "pr_auc": float(average_precision_score(y_true, probabilities))
        if has_two_classes
        else None,
        "roc_auc": float(roc_auc_score(y_true, probabilities)) if has_two_classes else None,
        "logloss": logloss_value,
        "accuracy": accuracy,
        "balanced_accuracy": balanced_accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "true_negative": true_negative,
        "false_positive": false_positive,
        "false_negative": false_negative,
        "true_positive": true_positive,
    }


def build_segment_performance(scores: pd.DataFrame, threshold: float) -> pd.DataFrame:
    rows: list[dict[str, object]] = []

    for split_name, split_frame in scores.groupby("split", dropna=False):
        rows.append(
            {
                "scope": "all_splits",
                "dimension": "split",
                "segment": split_name,
                **_metrics_for_frame(split_frame, threshold),
            }
        )

    test = scores.loc[scores["split"] == "test"].copy()
    rows.append(
        {
            "scope": "test",
            "dimension": "overall",
            "segment": "test_all",
            **_metrics_for_frame(test, threshold),
        }
    )

    for dimension in ["fiscal_year", "market", "industry_macro_category"]:
        for segment, segment_frame in test.groupby(dimension, dropna=False):
            rows.append(
                {
                    "scope": "test",
                    "dimension": dimension,
                    "segment": segment,
                    **_metrics_for_frame(segment_frame, threshold),
                }
            )

    return pd.DataFrame(rows)


def _threshold_grid(scores: pd.DataFrame, primary_threshold: float) -> list[float]:
    candidates = {primary_threshold, DEFAULT_THRESHOLD}
    threshold_column = scores.get("threshold")
    if threshold_column is not None:
        for value in threshold_column.dropna().unique():
            numeric = _safe_float(value)
            if numeric is not None:
                candidates.add(numeric)
    candidates.update(np.round(np.arange(0.1, 0.91, 0.05), 4).tolist())
    return sorted(float(value) for value in candidates if 0.0 < float(value) < 1.0)


def build_threshold_sweep(scores: pd.DataFrame, primary_threshold: float) -> pd.DataFrame:
    test = scores.loc[scores["split"] == "test"].copy()
    rows = []
    for threshold in _threshold_grid(scores, primary_threshold):
        row = _metrics_for_frame(test, threshold)
        row["threshold"] = threshold
        rows.append(row)
    return pd.DataFrame(rows).sort_values("threshold").reset_index(drop=True)


def build_calibration_bins(scores: pd.DataFrame) -> pd.DataFrame:
    rows: list[pd.DataFrame] = []
    bins = np.linspace(0.0, 1.0, 11)
    for split in ["valid", "test"]:
        frame = scores.loc[scores["split"] == split].copy()
        frame["probability_bin"] = pd.cut(
            frame["prob_speculative"],
            bins=bins,
            include_lowest=True,
            right=True,
        )
        grouped = (
            frame.groupby("probability_bin", observed=False)
            .agg(
                rows=("stock_code", "size"),
                mean_probability=("prob_speculative", "mean"),
                actual_positive_rate=("is_speculative", "mean"),
            )
            .reset_index()
        )
        grouped["split"] = split
        grouped["probability_bin"] = grouped["probability_bin"].astype(str)
        grouped["calibration_gap"] = grouped["mean_probability"] - grouped["actual_positive_rate"]
        rows.append(grouped)
    return pd.concat(rows, ignore_index=True).loc[
        :,
        [
            "split",
            "probability_bin",
            "rows",
            "mean_probability",
            "actual_positive_rate",
            "calibration_gap",
        ],
    ]


def _label_from_value(value: int) -> str:
    return "투기등급" if int(value) == 1 else "투자적격"


def build_error_cases(
    scores: pd.DataFrame,
    threshold: float,
    *,
    top_error_cases: int,
) -> pd.DataFrame:
    test = scores.loc[scores["split"] == "test"].copy()
    test["predicted_label"] = (test["prob_speculative"] >= threshold).astype(int)
    test["decision_threshold"] = threshold
    test["probability_distance_from_threshold"] = (test["prob_speculative"] - threshold).abs()
    test["actual_label_name"] = test["is_speculative"].map(_label_from_value)
    test["predicted_label_name"] = test["predicted_label"].map(_label_from_value)

    false_positive = (
        test.loc[(test["is_speculative"] == 0) & (test["predicted_label"] == 1)]
        .sort_values("prob_speculative", ascending=False)
        .head(top_error_cases)
        .copy()
    )
    false_positive["error_type"] = "false_positive"
    false_positive["error_note"] = "모델은 부적격으로 봤지만 실제 라벨은 투자적격"

    false_negative = (
        test.loc[(test["is_speculative"] == 1) & (test["predicted_label"] == 0)]
        .sort_values("prob_speculative", ascending=True)
        .head(top_error_cases)
        .copy()
    )
    false_negative["error_type"] = "false_negative"
    false_negative["error_note"] = "모델은 투자적격으로 봤지만 실제 라벨은 투기등급"

    error_cases = pd.concat([false_positive, false_negative], ignore_index=True)
    keep_columns = [
        "error_type",
        "error_note",
        "corp_name",
        "stock_code",
        "market",
        "fiscal_year",
        "eval_year",
        "industry_macro_category",
        "prob_speculative",
        "decision_threshold",
        "actual_label_name",
        "predicted_label_name",
        "probability_distance_from_threshold",
    ]
    for column in keep_columns:
        if column not in error_cases.columns:
            error_cases[column] = pd.NA
    return error_cases.loc[:, keep_columns]


def _best_threshold_row(threshold_sweep: pd.DataFrame, metric: str) -> dict[str, Any]:
    frame = threshold_sweep.dropna(subset=[metric])
    if frame.empty:
        return {}
    row = frame.sort_values([metric, "threshold"], ascending=[False, True]).iloc[0]
    return {key: row[key] for key in frame.columns}


def _weakest_segments(segment_performance: pd.DataFrame, top_n: int = 5) -> list[dict[str, Any]]:
    test_segments = segment_performance.loc[
        (segment_performance["scope"] == "test")
        & (segment_performance["dimension"].isin(["market", "industry_macro_category"]))
        & (segment_performance["positive_rows"] > 0)
        & (segment_performance["rows"] >= 20)
    ].copy()
    if test_segments.empty:
        return []
    return (
        test_segments.sort_values(["f1", "rows"], ascending=[True, False])
        .head(top_n)
        .to_dict(orient="records")
    )


def _probability_calibration_summary_from_scores(scores: pd.DataFrame) -> dict[str, object]:
    if "prob_speculative_raw" not in scores.columns:
        return {"method": "none"}

    from sklearn.metrics import brier_score_loss, log_loss

    method = "unknown"
    if "probability_calibration_method" in scores.columns:
        methods = scores["probability_calibration_method"].dropna().astype(str).unique()
        if len(methods):
            method = methods[0]

    summary: dict[str, object] = {"method": method}
    for split in ["valid", "test"]:
        frame = scores.loc[scores["split"] == split].copy()
        if frame.empty or frame["is_speculative"].nunique() < 2:
            continue
        y_true = frame["is_speculative"].astype(int)
        raw = pd.to_numeric(frame["prob_speculative_raw"], errors="coerce").to_numpy(dtype=float)
        calibrated = pd.to_numeric(frame["prob_speculative"], errors="coerce").to_numpy(dtype=float)
        raw = np.clip(raw, 1e-6, 1 - 1e-6)
        calibrated = np.clip(calibrated, 1e-6, 1 - 1e-6)
        summary[split] = {
            "brier_raw": float(brier_score_loss(y_true, raw)),
            "brier_calibrated": float(brier_score_loss(y_true, calibrated)),
            "logloss_raw": float(log_loss(y_true, raw)),
            "logloss_calibrated": float(log_loss(y_true, calibrated)),
        }
    return summary


def build_summary_payload(
    *,
    scores: pd.DataFrame,
    threshold: float,
    segment_performance: pd.DataFrame,
    threshold_sweep: pd.DataFrame,
    calibration_bins: pd.DataFrame,
    error_cases: pd.DataFrame,
    prediction_scores_path: Path,
) -> dict[str, Any]:
    test = scores.loc[scores["split"] == "test"].copy()
    primary_metrics = _metrics_for_frame(test, threshold)
    tuned_thresholds = sorted(
        {
            float(value)
            for value in scores.get("threshold", pd.Series(dtype=float)).dropna().unique()
            if _safe_float(value) is not None
        }
    )

    calibration_summary = (
        calibration_bins.loc[calibration_bins["split"] == "test"]
        .assign(abs_gap=lambda frame: frame["calibration_gap"].abs())
        .sort_values("abs_gap", ascending=False)
        .head(3)
        .drop(columns=["abs_gap"])
        .to_dict(orient="records")
    )

    return {
        "generated_at_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "dataset_name": "credit_43_features",
        "model_name": "feature_43_xgboost",
        "prediction_scores_path": str(prediction_scores_path.relative_to(ROOT)),
        "primary_threshold": threshold,
        "available_tuned_thresholds": tuned_thresholds,
        "primary_test_metrics": primary_metrics,
        "probability_calibration": _probability_calibration_summary_from_scores(scores),
        "best_f1_threshold": _best_threshold_row(threshold_sweep, "f1"),
        "best_balanced_accuracy_threshold": _best_threshold_row(
            threshold_sweep,
            "balanced_accuracy",
        ),
        "weakest_test_segments": _weakest_segments(segment_performance),
        "largest_test_calibration_gaps": calibration_summary,
        "error_case_counts": error_cases["error_type"].value_counts().to_dict(),
    }


def _format_number(value: object, digits: int = 4) -> str:
    numeric = _safe_float(value)
    if numeric is None:
        return "-"
    return f"{numeric:.{digits}f}"


def _format_count(value: object) -> str:
    numeric = _safe_float(value)
    if numeric is None:
        return "-"
    return f"{int(numeric):,}"


def _markdown_table(
    rows: list[dict[str, object]],
    columns: list[tuple[str, str, str]],
) -> str:
    header = "| " + " | ".join(label for label, _, _ in columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        values = []
        for _, key, kind in columns:
            value = row.get(key)
            if kind == "count":
                values.append(_format_count(value))
            elif kind == "metric":
                values.append(_format_number(value))
            elif kind == "percent":
                numeric = _safe_float(value)
                values.append("-" if numeric is None else f"{numeric * 100:.1f}%")
            else:
                values.append(str(value) if value is not None else "-")
        body.append("| " + " | ".join(values) + " |")
    return "\n".join([header, separator, *body])


def _records_for_dimension(
    segment_performance: pd.DataFrame, dimension: str
) -> list[dict[str, Any]]:
    return (
        segment_performance.loc[
            (segment_performance["scope"] == "test")
            & (segment_performance["dimension"] == dimension)
        ]
        .sort_values("segment")
        .to_dict(orient="records")
    )


def _top_error_records(
    error_cases: pd.DataFrame, error_type: str, top_n: int = 5
) -> list[dict[str, Any]]:
    return (
        error_cases.loc[error_cases["error_type"] == error_type]
        .head(top_n)
        .to_dict(orient="records")
    )


def build_markdown_report(
    *,
    summary: dict[str, Any],
    segment_performance: pd.DataFrame,
    threshold_sweep: pd.DataFrame,
    calibration_bins: pd.DataFrame,
    error_cases: pd.DataFrame,
) -> str:
    primary = summary["primary_test_metrics"]
    best_f1 = summary.get("best_f1_threshold", {})
    best_balanced = summary.get("best_balanced_accuracy_threshold", {})
    calibration = summary.get("probability_calibration", {})
    calibration_test = calibration.get("test", {}) if isinstance(calibration, dict) else {}

    threshold_rows = (
        threshold_sweep.loc[
            threshold_sweep["threshold"]
            .round(6)
            .isin([0.35, 0.4, 0.45, 0.5, round(float(best_f1.get("threshold", 0.5)), 6), 0.6, 0.65])
        ]
        .drop_duplicates("threshold")
        .sort_values("threshold")
        .to_dict(orient="records")
    )
    calibration_records = calibration_bins.loc[calibration_bins["split"] == "test"].to_dict(
        orient="records"
    )

    lines = [
        "# Feature 43 XGBoost Model Diagnostics",
        "",
        "이 리포트는 `prediction_scores.csv`를 기준으로 생성한 모델 진단 요약입니다.",
        "모델을 다시 학습하지 않고, 기존 예측 결과를 연도/시장/산업/threshold 관점에서",
        "나누어 확인합니다.",
        "",
        "## 1. Test 전체 성능",
        "",
        _markdown_table(
            [primary],
            [
                ("Rows", "rows", "count"),
                ("Positive", "positive_rows", "count"),
                ("Positive Rate", "positive_rate", "percent"),
                ("PR-AUC", "pr_auc", "metric"),
                ("ROC-AUC", "roc_auc", "metric"),
                ("Precision", "precision", "metric"),
                ("Recall", "recall", "metric"),
                ("F1", "f1", "metric"),
                ("FP", "false_positive", "count"),
                ("FN", "false_negative", "count"),
            ],
        ),
        "",
        "## 2. Threshold별 trade-off",
        "",
        f"- 현재 기준 threshold: `{_format_number(summary['primary_threshold'])}`",
        (
            "- F1 기준 최적 후보: "
            f"`{_format_number(best_f1.get('threshold'))}` "
            f"(F1 `{_format_number(best_f1.get('f1'))}`, "
            f"Precision `{_format_number(best_f1.get('precision'))}`, "
            f"Recall `{_format_number(best_f1.get('recall'))}`)"
        ),
        (
            "- Balanced Accuracy 기준 최적 후보: "
            f"`{_format_number(best_balanced.get('threshold'))}` "
            f"(Balanced Accuracy `{_format_number(best_balanced.get('balanced_accuracy'))}`)"
        ),
        "",
        _markdown_table(
            threshold_rows,
            [
                ("Threshold", "threshold", "metric"),
                ("Precision", "precision", "metric"),
                ("Recall", "recall", "metric"),
                ("F1", "f1", "metric"),
                ("Balanced Acc.", "balanced_accuracy", "metric"),
                ("FP", "false_positive", "count"),
                ("FN", "false_negative", "count"),
            ],
        ),
        "",
        "## 3. 시장별 Test 성능",
        "",
        _markdown_table(
            _records_for_dimension(segment_performance, "market"),
            [
                ("Market", "segment", "text"),
                ("Rows", "rows", "count"),
                ("Positive Rate", "positive_rate", "percent"),
                ("PR-AUC", "pr_auc", "metric"),
                ("ROC-AUC", "roc_auc", "metric"),
                ("Precision", "precision", "metric"),
                ("Recall", "recall", "metric"),
                ("F1", "f1", "metric"),
                ("FP", "false_positive", "count"),
                ("FN", "false_negative", "count"),
            ],
        ),
        "",
        "## 4. 산업별 Test 성능",
        "",
        _markdown_table(
            _records_for_dimension(segment_performance, "industry_macro_category"),
            [
                ("Industry", "segment", "text"),
                ("Rows", "rows", "count"),
                ("Positive Rate", "positive_rate", "percent"),
                ("PR-AUC", "pr_auc", "metric"),
                ("ROC-AUC", "roc_auc", "metric"),
                ("Precision", "precision", "metric"),
                ("Recall", "recall", "metric"),
                ("F1", "f1", "metric"),
                ("FP", "false_positive", "count"),
                ("FN", "false_negative", "count"),
            ],
        ),
        "",
        "## 5. Test 확률 보정 점검",
        "",
        (
            "- 보정 방식: "
            f"`{calibration.get('method', 'none') if isinstance(calibration, dict) else 'none'}`"
        ),
        (
            "- Test Brier score: "
            f"raw `{_format_number(calibration_test.get('brier_raw'))}` → "
            f"calibrated `{_format_number(calibration_test.get('brier_calibrated'))}`"
        ),
        (
            "- Test logloss: "
            f"raw `{_format_number(calibration_test.get('logloss_raw'))}` → "
            f"calibrated `{_format_number(calibration_test.get('logloss_calibrated'))}`"
        ),
        "",
        "mean_probability는 모델 평균 예측확률이고 actual_positive_rate는 실제 투기등급 비율입니다.",
        "",
        _markdown_table(
            calibration_records,
            [
                ("Probability Bin", "probability_bin", "text"),
                ("Rows", "rows", "count"),
                ("Mean Prob.", "mean_probability", "metric"),
                ("Actual Rate", "actual_positive_rate", "metric"),
                ("Gap", "calibration_gap", "metric"),
            ],
        ),
        "",
        "## 6. 대표 오류 사례",
        "",
        "False Positive는 모델이 위험하다고 봤지만 실제 라벨은 투자적격인 사례입니다.",
        "",
        _markdown_table(
            _top_error_records(error_cases, "false_positive"),
            [
                ("Company", "corp_name", "text"),
                ("Code", "stock_code", "text"),
                ("Market", "market", "text"),
                ("Year", "fiscal_year", "text"),
                ("Industry", "industry_macro_category", "text"),
                ("Prob.", "prob_speculative", "metric"),
            ],
        ),
        "",
        "False Negative는 모델이 안정적으로 봤지만 실제 라벨은 투기등급인 사례입니다.",
        "",
        _markdown_table(
            _top_error_records(error_cases, "false_negative"),
            [
                ("Company", "corp_name", "text"),
                ("Code", "stock_code", "text"),
                ("Market", "market", "text"),
                ("Year", "fiscal_year", "text"),
                ("Industry", "industry_macro_category", "text"),
                ("Prob.", "prob_speculative", "metric"),
            ],
        ),
        "",
        "## 7. 다음 개선 후보",
        "",
        "- KOSDAQ과 IT 서비스처럼 precision이 낮은 구간을 별도로 점검합니다.",
        "- Platt scaling 이후에도 차이가 남는 확률 구간은 표본 수와 산업 구성을 함께 점검합니다.",
        "- 반복적으로 발생하는 false positive/false negative 기업은 SHAP과 외부근거를 함께 확인합니다.",
        "- 발표용으로는 전체 성능뿐 아니라 취약 구간과 보완 계획을 함께 제시하는 편이 좋습니다.",
        "",
    ]
    return "\n".join(lines)


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    prediction_scores_path = args.prediction_scores.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    scores = _read_prediction_scores(prediction_scores_path)
    threshold = _resolve_primary_threshold(scores, args.threshold)
    segment_performance = build_segment_performance(scores, threshold)
    threshold_sweep = build_threshold_sweep(scores, threshold)
    calibration_bins = build_calibration_bins(scores)
    error_cases = build_error_cases(
        scores,
        threshold,
        top_error_cases=args.top_error_cases,
    )
    summary = build_summary_payload(
        scores=scores,
        threshold=threshold,
        segment_performance=segment_performance,
        threshold_sweep=threshold_sweep,
        calibration_bins=calibration_bins,
        error_cases=error_cases,
        prediction_scores_path=prediction_scores_path,
    )
    markdown_report = build_markdown_report(
        summary=summary,
        segment_performance=segment_performance,
        threshold_sweep=threshold_sweep,
        calibration_bins=calibration_bins,
        error_cases=error_cases,
    )

    segment_performance.to_csv(
        output_dir / "segment_performance.csv",
        index=False,
        encoding="utf-8-sig",
    )
    threshold_sweep.to_csv(output_dir / "threshold_sweep.csv", index=False, encoding="utf-8-sig")
    calibration_bins.to_csv(
        output_dir / "calibration_bins.csv",
        index=False,
        encoding="utf-8-sig",
    )
    error_cases.to_csv(output_dir / "error_cases.csv", index=False, encoding="utf-8-sig")
    write_json(output_dir / "model_diagnostics_summary.json", summary)
    (output_dir / "model_diagnostics_report.md").write_text(markdown_report, encoding="utf-8")

    print(f"feature_43 model diagnostics written to: {output_dir}")


if __name__ == "__main__":
    main()
