from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_DIR = ROOT / "data" / "outputs" / "dashboard" / "feature_46_mvp"
PREDICTION_SCORES_PATH = DASHBOARD_DIR / "prediction_scores.csv"
LOCAL_SHAP_PATH = DASHBOARD_DIR / "local_shap.csv"
FEATURE_DICTIONARY_PATH = DASHBOARD_DIR / "feature_dictionary.csv"
OUTPUT_DIR = ROOT / "data" / "outputs" / "modeling" / "feature_46_xgboost" / "diagnostics"

CASE_KEYS = ["market", "stock_code_norm", "corp_name", "fiscal_year", "eval_year"]
TOP_CASES_PER_ERROR = 10
TOP_FEATURES_PER_CASE = 5


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export SHAP diagnostics for false positive/false negative cases."
    )
    parser.add_argument(
        "--prediction-scores",
        type=Path,
        default=PREDICTION_SCORES_PATH,
        help="prediction_scores.csv generated by export_feature_43_dashboard_artifacts.py.",
    )
    parser.add_argument(
        "--local-shap",
        type=Path,
        default=LOCAL_SHAP_PATH,
        help="local_shap.csv generated by export_feature_43_dashboard_artifacts.py.",
    )
    parser.add_argument(
        "--feature-dictionary",
        type=Path,
        default=FEATURE_DICTIONARY_PATH,
        help="feature_dictionary.csv generated by export_feature_43_dashboard_artifacts.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Directory where error SHAP diagnostics will be written.",
    )
    return parser.parse_args()


def _normalize_stock_code(series: pd.Series) -> pd.Series:
    return (
        series.astype(str)
        .str.replace(r"\.0$", "", regex=True)
        .str.replace(r"\D", "", regex=True)
        .str.zfill(6)
    )


def _read_prediction_scores(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Prediction scores file not found: {path}")
    frame = pd.read_csv(path, encoding="utf-8-sig")
    required_columns = {
        "market",
        "stock_code",
        "corp_name",
        "fiscal_year",
        "eval_year",
        "firm_size_group",
        "industry_macro_category",
        "split",
        "is_speculative",
        "prob_speculative",
        "threshold",
    }
    missing_columns = sorted(required_columns - set(frame.columns))
    if missing_columns:
        raise KeyError(f"prediction_scores.csv is missing required columns: {missing_columns}")
    frame = frame.copy()
    frame["stock_code_norm"] = _normalize_stock_code(frame["stock_code"])
    frame["is_speculative"] = frame["is_speculative"].astype(int)
    frame["prob_speculative"] = pd.to_numeric(frame["prob_speculative"], errors="coerce")
    frame["threshold"] = pd.to_numeric(frame["threshold"], errors="coerce")
    return frame


def _read_local_shap(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Local SHAP file not found: {path}")
    frame = pd.read_csv(path, encoding="utf-8-sig")
    required_columns = {
        "market",
        "stock_code",
        "corp_name",
        "fiscal_year",
        "eval_year",
        "feature",
        "rank",
        "shap_value",
        "abs_shap",
        "direction",
        "feature_value",
    }
    missing_columns = sorted(required_columns - set(frame.columns))
    if missing_columns:
        raise KeyError(f"local_shap.csv is missing required columns: {missing_columns}")
    frame = frame.copy()
    frame["stock_code_norm"] = _normalize_stock_code(frame["stock_code"])
    frame["rank"] = pd.to_numeric(frame["rank"], errors="coerce")
    frame["shap_value"] = pd.to_numeric(frame["shap_value"], errors="coerce")
    frame["abs_shap"] = pd.to_numeric(frame["abs_shap"], errors="coerce")
    return frame


def _read_feature_dictionary(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Feature dictionary file not found: {path}")
    frame = pd.read_csv(path, encoding="utf-8-sig")
    return frame.loc[:, ["feature", "feature_group", "korean_name", "description"]].copy()


def build_error_cases(scores: pd.DataFrame) -> tuple[pd.DataFrame, float]:
    test_scores = scores.loc[scores["split"] == "test"].copy()
    if test_scores.empty:
        raise ValueError("prediction_scores.csv must contain test split rows.")
    threshold_candidates = test_scores["threshold"].dropna().unique()
    threshold = float(threshold_candidates[0]) if len(threshold_candidates) else 0.5
    test_scores["predicted_current"] = (test_scores["prob_speculative"] >= threshold).astype(int)
    test_scores["error_type"] = "correct"
    test_scores.loc[
        test_scores["is_speculative"].eq(0) & test_scores["predicted_current"].eq(1),
        "error_type",
    ] = "false_positive"
    test_scores.loc[
        test_scores["is_speculative"].eq(1) & test_scores["predicted_current"].eq(0),
        "error_type",
    ] = "false_negative"
    test_scores["actual_label_name"] = np.where(
        test_scores["is_speculative"].eq(1),
        "투기등급",
        "투자적격",
    )
    test_scores["predicted_label_name"] = np.where(
        test_scores["predicted_current"].eq(1),
        "투기등급",
        "투자적격",
    )
    test_scores["probability_distance_from_threshold"] = (
        test_scores["prob_speculative"] - threshold
    ).abs()
    errors = test_scores.loc[test_scores["error_type"].ne("correct")].copy()
    return errors, threshold


def build_case_details(
    *,
    errors: pd.DataFrame,
    local_shap: pd.DataFrame,
    feature_dictionary: pd.DataFrame,
) -> pd.DataFrame:
    error_columns = [
        *CASE_KEYS,
        "firm_size_group",
        "industry_macro_category",
        "error_type",
        "is_speculative",
        "predicted_current",
        "actual_label_name",
        "predicted_label_name",
        "prob_speculative",
        "threshold",
        "probability_distance_from_threshold",
    ]
    details = local_shap.merge(
        errors.loc[:, error_columns],
        on=CASE_KEYS,
        how="inner",
        suffixes=("", "_score"),
    )
    details = details.merge(feature_dictionary, on="feature", how="left")
    details["korean_name"] = details["korean_name"].fillna(details["feature"])
    details["feature_group"] = details["feature_group"].fillna("unknown")
    details["case_id"] = details[CASE_KEYS].astype(str).agg("|".join, axis=1)
    details = details.sort_values(
        ["error_type", "probability_distance_from_threshold", *CASE_KEYS, "rank"],
        ascending=[True, False, *([True] * (len(CASE_KEYS) + 1))],
    )
    return details


def build_feature_summary(details: pd.DataFrame) -> pd.DataFrame:
    case_counts = details.groupby("error_type")["case_id"].nunique().to_dict()
    summary = (
        details.groupby(["error_type", "feature", "direction"], dropna=False)
        .agg(
            case_count=("case_id", "nunique"),
            appearance_count=("feature", "size"),
            mean_abs_shap=("abs_shap", "mean"),
            mean_shap_value=("shap_value", "mean"),
            median_rank=("rank", "median"),
            feature_group=("feature_group", "first"),
            korean_name=("korean_name", "first"),
            description=("description", "first"),
        )
        .reset_index()
    )
    summary["case_share"] = summary.apply(
        lambda row: row["case_count"] / case_counts.get(row["error_type"], 1),
        axis=1,
    )
    return summary.sort_values(
        ["error_type", "case_count", "mean_abs_shap"],
        ascending=[True, False, False],
    )


def build_segment_summary(test_scores: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for dimension in ["market", "industry_macro_category"]:
        for segment, segment_frame in test_scores.groupby(dimension, dropna=False):
            total_rows = len(segment_frame)
            false_positive = int(segment_frame["error_type"].eq("false_positive").sum())
            false_negative = int(segment_frame["error_type"].eq("false_negative").sum())
            positive_rows = int(segment_frame["is_speculative"].sum())
            negative_rows = total_rows - positive_rows
            rows.append(
                {
                    "dimension": dimension,
                    "segment": str(segment),
                    "rows": total_rows,
                    "positive_rows": positive_rows,
                    "negative_rows": negative_rows,
                    "false_positive": false_positive,
                    "false_negative": false_negative,
                    "fp_rate_among_negative": false_positive / negative_rows
                    if negative_rows
                    else None,
                    "fn_rate_among_positive": false_negative / positive_rows
                    if positive_rows
                    else None,
                }
            )
    return pd.DataFrame(rows).sort_values(
        ["false_positive", "false_negative", "rows"],
        ascending=False,
    )


def build_top_cases(details: pd.DataFrame) -> pd.DataFrame:
    top_case_rows: list[dict[str, object]] = []
    ordered_cases = (
        details.loc[:, [*CASE_KEYS, "error_type", "probability_distance_from_threshold"]]
        .drop_duplicates()
        .sort_values(
            ["error_type", "probability_distance_from_threshold"],
            ascending=[True, False],
        )
    )
    for error_type, frame in ordered_cases.groupby("error_type", sort=False):
        for _, case_row in frame.head(TOP_CASES_PER_ERROR).iterrows():
            mask = pd.Series(True, index=details.index)
            for key in CASE_KEYS:
                mask &= details[key].eq(case_row[key])
            case_details = details.loc[mask].sort_values("rank")
            first = case_details.iloc[0]
            top_features = [
                (
                    f"{row.korean_name}"
                    f"({row.direction}, SHAP={float(row.shap_value):+.3f}, 값={row.feature_value})"
                )
                for row in case_details.head(TOP_FEATURES_PER_CASE).itertuples()
            ]
            top_case_rows.append(
                {
                    "error_type": error_type,
                    "market": first["market"],
                    "stock_code": first["stock_code_norm"],
                    "corp_name": first["corp_name"],
                    "fiscal_year": int(first["fiscal_year"]),
                    "eval_year": int(first["eval_year"]),
                    "industry_macro_category": first["industry_macro_category"],
                    "firm_size_group": first["firm_size_group"],
                    "prob_speculative": float(first["prob_speculative"]),
                    "threshold": float(first["threshold"]),
                    "probability_distance_from_threshold": float(
                        first["probability_distance_from_threshold"]
                    ),
                    "actual_label_name": first["actual_label_name"],
                    "predicted_label_name": first["predicted_label_name"],
                    "top_shap_features": "; ".join(top_features),
                }
            )
    return pd.DataFrame(top_case_rows)


def _format_number(value: object, digits: int = 4) -> str:
    if value is None:
        return "-"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "-"
    if np.isnan(numeric):
        return "-"
    return f"{numeric:.{digits}f}"


def _format_percent(value: object) -> str:
    if value is None:
        return "-"
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "-"
    if np.isnan(numeric):
        return "-"
    return f"{numeric * 100:.1f}%"


def _build_feature_table(summary: pd.DataFrame, error_type: str, direction: str) -> str:
    frame = summary.loc[
        summary["error_type"].eq(error_type) & summary["direction"].eq(direction)
    ].head(10)
    rows = [
        "| Feature | Direction | Cases | Share | Mean | Rank | 해석 포인트 |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for row in frame.itertuples():
        rows.append(
            "| {feature} | {direction} | {cases} | {share} | {mean} | {rank} | {description} |".format(
                feature=row.korean_name,
                direction=row.direction,
                cases=int(row.case_count),
                share=_format_percent(row.case_share),
                mean=_format_number(row.mean_shap_value),
                rank=_format_number(row.median_rank, 1),
                description=str(row.description)[:60] if pd.notna(row.description) else "",
            )
        )
    return "\n".join(rows)


def _build_segment_table(segment_summary: pd.DataFrame) -> str:
    focus = segment_summary.loc[
        segment_summary["segment"].isin(["KOSDAQ", "KOSPI", "it_services", "manufacturing"])
    ]
    rows = [
        "| Segment | Rows | FP | FP Rate | FN | FN Rate |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in focus.itertuples():
        rows.append(
            "| {segment} | {rows} | {fp} | {fp_rate} | {fn} | {fn_rate} |".format(
                segment=f"{row.dimension}={row.segment}",
                rows=int(row.rows),
                fp=int(row.false_positive),
                fp_rate=_format_percent(row.fp_rate_among_negative),
                fn=int(row.false_negative),
                fn_rate=_format_percent(row.fn_rate_among_positive),
            )
        )
    return "\n".join(rows)


def _build_case_table(top_cases: pd.DataFrame, error_type: str) -> str:
    frame = top_cases.loc[top_cases["error_type"].eq(error_type)].head(5)
    rows = [
        "| Company | Market | Year | Prob. | Actual | Pred. | Top SHAP |",
        "| --- | --- | ---: | ---: | --- | --- | --- |",
    ]
    for row in frame.itertuples():
        rows.append(
            f"| {row.corp_name} | {row.market} | {int(row.fiscal_year)} | "
            f"{_format_number(row.prob_speculative)} | {row.actual_label_name} | "
            f"{row.predicted_label_name} | {row.top_shap_features} |"
        )
    return "\n".join(rows)


def build_report(
    *,
    threshold: float,
    errors: pd.DataFrame,
    feature_summary: pd.DataFrame,
    segment_summary: pd.DataFrame,
    top_cases: pd.DataFrame,
) -> str:
    false_positive_count = int(errors["error_type"].eq("false_positive").sum())
    false_negative_count = int(errors["error_type"].eq("false_negative").sum())
    kosdaq_fp = int(
        errors["error_type"].eq("false_positive").mul(errors["market"].eq("KOSDAQ")).sum()
    )
    manufacturing_fp = int(
        errors["error_type"]
        .eq("false_positive")
        .mul(errors["industry_macro_category"].eq("manufacturing"))
        .sum()
    )

    return f"""# Feature 43 Error Case SHAP Analysis

이 리포트는 현재 Stage 1 운영 threshold `{threshold:.3f}` 기준의 false positive와
false negative를 `local_shap.csv`와 연결해, 모델이 왜 틀렸는지 확인하기 위한
진단 산출물입니다.

## 1. 오류 규모

- False Positive: `{false_positive_count}`개
- False Negative: `{false_negative_count}`개
- KOSDAQ False Positive: `{kosdaq_fp}`개
- Manufacturing False Positive: `{manufacturing_fp}`개

## 2. 오류 집중 세그먼트

{_build_segment_table(segment_summary)}

## 3. False Positive 공통 SHAP 패턴

모델이 위험하다고 봤지만 실제 라벨은 투자적격인 사례입니다.

위험을 높인 주요 요인:

{_build_feature_table(feature_summary, "false_positive", "increase_risk")}

위험을 낮춘 주요 요인:

{_build_feature_table(feature_summary, "false_positive", "decrease_risk")}

## 4. False Negative 공통 SHAP 패턴

모델이 안정적으로 봤지만 실제 라벨은 투기등급인 사례입니다.

위험을 낮춘 주요 요인:

{_build_feature_table(feature_summary, "false_negative", "decrease_risk")}

위험을 높인 주요 요인:

{_build_feature_table(feature_summary, "false_negative", "increase_risk")}

## 5. 대표 False Positive 사례

{_build_case_table(top_cases, "false_positive")}

## 6. 대표 False Negative 사례

{_build_case_table(top_cases, "false_negative")}

## 7. 개선 후보

- False Positive는 `gross_profit`, `assets_total`, `depreciation` 같은 규모성 원천값과
  `firm_size_group`, `listed_year` 같은 맥락 변수가 반복적으로 위험을 키우는 패턴이
  나타납니다. 규모가 작은 KOSDAQ/제조업 기업에서 절대금액이 위험 신호처럼 작동하는지
  추가 점검이 필요합니다.
- False Negative는 대기업·대규모 자산·배당 지급·자본잠식률 안정 신호가 위험을 강하게
  낮추는 패턴이 나타납니다. 대기업 이벤트성 등급 하락이나 일시적 외부 충격은 재무제표
  기반 모델만으로 놓칠 수 있어 외부근거/공시 신호와 결합하는 편이 좋습니다.
- 다음 변수 실험은 핵심 비율의 산업-연도 내 백분위, 규모 조정 로그 변수,
  최근 악화 속도 변수, 외부 공시 위험 신호 플래그 순서로 진행하는 것이 적절합니다.

## 8. 산출물

- `error_shap_case_details.csv`: 오류 사례별 top SHAP 상세
- `error_shap_feature_summary.csv`: FP/FN별 공통 SHAP 요인 집계
- `error_shap_segment_summary.csv`: 시장/산업별 FP/FN 집중도
- `error_shap_top_cases.csv`: 대표 오류 사례와 상위 SHAP 요인
- `error_shap_analysis_summary.json`: 주요 요약 수치
"""


def build_summary_payload(
    *,
    threshold: float,
    errors: pd.DataFrame,
    feature_summary: pd.DataFrame,
    segment_summary: pd.DataFrame,
) -> dict[str, Any]:
    def json_safe(value: object) -> object:
        if isinstance(value, float) and np.isnan(value):
            return None
        if isinstance(value, dict):
            return {key: json_safe(item) for key, item in value.items()}
        if isinstance(value, list):
            return [json_safe(item) for item in value]
        return value

    def top_features(error_type: str, direction: str) -> list[dict[str, object]]:
        frame = feature_summary.loc[
            feature_summary["error_type"].eq(error_type)
            & feature_summary["direction"].eq(direction)
        ].head(10)
        return [
            {
                "feature": row.feature,
                "korean_name": row.korean_name,
                "case_count": int(row.case_count),
                "case_share": float(row.case_share),
                "mean_shap_value": float(row.mean_shap_value),
                "median_rank": float(row.median_rank),
            }
            for row in frame.itertuples()
        ]

    return {
        "generated_at": datetime.now(tz=UTC).isoformat(),
        "threshold": threshold,
        "false_positive_count": int(errors["error_type"].eq("false_positive").sum()),
        "false_negative_count": int(errors["error_type"].eq("false_negative").sum()),
        "segment_summary": json_safe(segment_summary.to_dict(orient="records")),
        "false_positive_top_increase_risk_features": top_features(
            "false_positive",
            "increase_risk",
        ),
        "false_negative_top_decrease_risk_features": top_features(
            "false_negative",
            "decrease_risk",
        ),
    }


def write_outputs(
    *,
    output_dir: Path,
    threshold: float,
    errors: pd.DataFrame,
    case_details: pd.DataFrame,
    feature_summary: pd.DataFrame,
    segment_summary: pd.DataFrame,
    top_cases: pd.DataFrame,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    case_details.to_csv(
        output_dir / "error_shap_case_details.csv", index=False, encoding="utf-8-sig"
    )
    feature_summary.to_csv(
        output_dir / "error_shap_feature_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )
    segment_summary.to_csv(
        output_dir / "error_shap_segment_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )
    top_cases.to_csv(output_dir / "error_shap_top_cases.csv", index=False, encoding="utf-8-sig")
    summary = build_summary_payload(
        threshold=threshold,
        errors=errors,
        feature_summary=feature_summary,
        segment_summary=segment_summary,
    )
    (output_dir / "error_shap_analysis_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (output_dir / "error_shap_analysis_report.md").write_text(
        build_report(
            threshold=threshold,
            errors=errors,
            feature_summary=feature_summary,
            segment_summary=segment_summary,
            top_cases=top_cases,
        ),
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    scores = _read_prediction_scores(args.prediction_scores)
    local_shap = _read_local_shap(args.local_shap)
    feature_dictionary = _read_feature_dictionary(args.feature_dictionary)
    errors, threshold = build_error_cases(scores)
    case_details = build_case_details(
        errors=errors,
        local_shap=local_shap,
        feature_dictionary=feature_dictionary,
    )
    test_scores = scores.loc[scores["split"].eq("test")].copy()
    test_scores = test_scores.merge(
        errors.loc[:, [*CASE_KEYS, "error_type"]],
        on=CASE_KEYS,
        how="left",
    )
    test_scores["error_type"] = test_scores["error_type"].fillna("correct")
    feature_summary = build_feature_summary(case_details)
    segment_summary = build_segment_summary(test_scores)
    top_cases = build_top_cases(case_details)
    write_outputs(
        output_dir=args.output_dir,
        threshold=threshold,
        errors=errors,
        case_details=case_details,
        feature_summary=feature_summary,
        segment_summary=segment_summary,
        top_cases=top_cases,
    )
    print(f"Wrote error SHAP diagnostics to {args.output_dir}")


if __name__ == "__main__":
    main()
