"""Compatibility exports for post-committee QA helpers.

The ReviewQA and RiskRecallQA implementations live in focused modules:

- qa_cache.py: runtime config and LLM cache boundaries
- qa_diagnostics.py: diagnostic merge and text helpers
- review_qa_policy.py: over-hold/reject mitigation policy
- risk_recall_policy.py: eligible-case recall policy
"""

from __future__ import annotations

from cas.agents.nodes.qa_cache import (
    _REVIEW_QA_CACHE_VERSION,
    _RISK_RECALL_QA_CACHE_VERSION,
    _review_qa_cache_payload,
    _risk_recall_qa_cache_payload,
    _run_review_qa_agent_with_cache,
    _run_risk_recall_qa_agent_with_cache,
    _stage2_review_qa_max_tokens,
    _stage2_review_qa_model,
    _stage2_review_qa_provider,
    _stage2_risk_recall_qa_max_tokens,
    _stage2_risk_recall_qa_model,
    _stage2_risk_recall_qa_provider,
    _stage2_runtime_config,
    post_committee_runtime_config_override,
    run_cached_optional_agent,
)
from cas.agents.nodes.qa_diagnostics import (
    _append_sentence,
    _merge_post_committee_qa_diagnostics,
    _merge_review_qa_diagnostics,
    _prepend_unique_text,
)
from cas.agents.nodes.review_qa_policy import (
    _agent_disagreement_level_from_committee_view,
    _agent_disagreement_reasons_from_committee_view,
    _apply_review_qa_advisory,
    _apply_review_qa_reject_advisory,
    _apply_review_qa_risk_hold_advisory,
    _external_evidence_is_watch_context_only,
    _has_review_qa_extreme_financial_distress,
    _has_review_qa_reject_boundary_defense,
    _has_review_qa_risk_hold_boundary_defense,
    _is_watch_context_external_item,
    _maybe_run_review_qa,
    _review_qa_advisory_apply_reason,
    _review_qa_disagreement_allows_reject,
    _review_qa_disagreement_allows_risk_hold,
    _review_qa_memo_conflict_possible,
    _review_qa_reject_advisory_apply_reason,
    _review_qa_trigger_reasons,
    _stage2_review_qa_apply_advisory,
    _stage2_review_qa_enabled,
    _stage2_review_qa_fallback_on_error,
)
from cas.agents.nodes.risk_recall_policy import (
    _apply_deterministic_risk_recall_guardrail,
    _apply_risk_recall_qa_advisory,
    _deterministic_risk_recall_guardrail_apply_reason,
    _has_rating_boundary_context,
    _has_risk_recall_watch_evidence,
    _maybe_run_risk_recall_qa,
    _neutralize_prior_eligible_final_memo,
    _risk_recall_confirmed_external_escalation_evidence,
    _risk_recall_evidence_item_is_confirmed,
    _risk_recall_hold_reason_fields,
    _risk_recall_near_threshold,
    _risk_recall_qa_advisory_apply_reason,
    _risk_recall_qa_trigger_reasons,
    _risk_recall_weak_financial_axes,
    _stage2_risk_recall_qa_apply_advisory,
    _stage2_risk_recall_qa_enabled,
    _stage2_risk_recall_qa_fallback_on_error,
)

__all__ = [
    "_REVIEW_QA_CACHE_VERSION",
    "_RISK_RECALL_QA_CACHE_VERSION",
    "_agent_disagreement_level_from_committee_view",
    "_agent_disagreement_reasons_from_committee_view",
    "_append_sentence",
    "_apply_deterministic_risk_recall_guardrail",
    "_apply_review_qa_advisory",
    "_apply_review_qa_reject_advisory",
    "_apply_review_qa_risk_hold_advisory",
    "_apply_risk_recall_qa_advisory",
    "_deterministic_risk_recall_guardrail_apply_reason",
    "_external_evidence_is_watch_context_only",
    "_has_rating_boundary_context",
    "_has_review_qa_extreme_financial_distress",
    "_has_review_qa_reject_boundary_defense",
    "_has_review_qa_risk_hold_boundary_defense",
    "_has_risk_recall_watch_evidence",
    "_is_watch_context_external_item",
    "_maybe_run_review_qa",
    "_maybe_run_risk_recall_qa",
    "_merge_post_committee_qa_diagnostics",
    "_merge_review_qa_diagnostics",
    "_neutralize_prior_eligible_final_memo",
    "_prepend_unique_text",
    "_review_qa_advisory_apply_reason",
    "_review_qa_cache_payload",
    "_review_qa_disagreement_allows_reject",
    "_review_qa_disagreement_allows_risk_hold",
    "_review_qa_memo_conflict_possible",
    "_review_qa_reject_advisory_apply_reason",
    "_review_qa_trigger_reasons",
    "_risk_recall_confirmed_external_escalation_evidence",
    "_risk_recall_evidence_item_is_confirmed",
    "_risk_recall_hold_reason_fields",
    "_risk_recall_near_threshold",
    "_risk_recall_qa_advisory_apply_reason",
    "_risk_recall_qa_cache_payload",
    "_risk_recall_qa_trigger_reasons",
    "_risk_recall_weak_financial_axes",
    "_run_review_qa_agent_with_cache",
    "_run_risk_recall_qa_agent_with_cache",
    "_stage2_review_qa_apply_advisory",
    "_stage2_review_qa_enabled",
    "_stage2_review_qa_fallback_on_error",
    "_stage2_review_qa_max_tokens",
    "_stage2_review_qa_model",
    "_stage2_review_qa_provider",
    "_stage2_risk_recall_qa_apply_advisory",
    "_stage2_risk_recall_qa_enabled",
    "_stage2_risk_recall_qa_fallback_on_error",
    "_stage2_risk_recall_qa_max_tokens",
    "_stage2_risk_recall_qa_model",
    "_stage2_risk_recall_qa_provider",
    "_stage2_runtime_config",
    "post_committee_runtime_config_override",
    "run_cached_optional_agent",
]
